apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patchesStrategicMerge:
  - "service.yaml"
  - "deployment.yaml"
  - "configMap.yaml"
namePrefix: dev-rtc-
namespace: dev
commonLabels:
  environment: dev